# python-eduvpn-client - The GNU/Linux eduVPN client and Python API
#
# Copyright: 2017, The Commons Conservancy eduVPN Programme
# SPDX-License-Identifier: GPL-3.0+

def choice_window(options, meta, oauth, builder): ...
def background(meta, oauth, builder): ...
def two_auth_step(builder, oauth, meta): ...
