# python-eduvpn-client - The GNU/Linux eduVPN client and Python API
#
# Copyright: 2017, The Commons Conservancy eduVPN Programme
# SPDX-License-Identifier: GPL-3.0+

def _choice_window(options, meta, oauth, builder, config_dict: dict): ...
def _background(meta, oauth, builder, config_dict: dict): ...
def two_auth_step(builder, oauth, meta, config_dict: dict): ...
