FROM fedora:26

RUN dnf install -y \
        python2-pydbus \
        python2-pynacl \
        python2-requests-oauthlib \
        python-gobject \
        python2-pip \
        python2-configparser \
        python2-future \
        python2-nose \
        python2-mock \
        python2-dateutil

ADD . /code
WORKDIR /code
RUN pip install .
