FROM fedora:26

RUN dnf install -y \
        python3-networkmanager \
        python3-pydbus \
        python3-pynacl \
        python3-requests-oauthlib \
        python3-gobject \
	    python3-pip \
        python3-configparser \
        python3-future \
        python3-nose \
        python3-mock

ADD . /code
WORKDIR /code
RUN pip3 install .
