FROM centos:7

RUN yum install -y epel-release

RUN yum install -y \
        python2-pydbus \
        python2-pynacl \
        python2-requests-oauthlib \
        python-gobject \
        python2-pip \
        python2-configparser \
        python2-future \
        python2-mock \
        python3-dateutil \

ADD . /code
WORKDIR /code
RUN pip install .
