FROM ubuntu:xenial

ADD docker/docker-apt-install /usr/local/bin/docker-apt-install
RUN docker-apt-install \
        python-dbus \
        python-nacl \
        python-requests-oauthlib \
        python-gi \
        python-pip \
        python-configparser \
        python-future \
        python-nose \
        python-mock \
        python-dateutil

ADD . /code
WORKDIR /code
RUN pip install .

