FROM ubuntu:xenial

ADD docker/docker-apt-install /usr/local/bin/docker-apt-install
RUN docker-apt-install \
        gir1.2-gtk-3.0 \
        gir1.2-notify-0.7 \
        python3-gi \
        python3-dbus \
        python3-nacl \
        python3-requests-oauthlib \
        python3-future \
        python3-dateutil \
        python3-pip \
        python3-mock \
        python3-pytest

ADD . /code
WORKDIR /code
RUN python setup.py install
RUN python3 setup.py test
