FROM fedora:25

RUN dnf install -y \
        python2-networkmanager \
        python2-pydbus \
        python2-pynacl \
        python2-requests-oauthlib \
        python-gobject \
	    python-pip \
        python2-configparser \
        python2-future \
        python2-nose \
        python2-mock

ADD . /code
WORKDIR /code
RUN pip install .
