FROM fedora:25

RUN dnf install -y \
        libnotify \
        gtk3 \
        python3-dbus \
        python3-pynacl \
        python3-requests-oauthlib \
        python3-repoze-lru \
        python3-gobject \
        python3-future \
        python3-dateutil \
        python3-mock \
        python3-pytest

ADD . /code
WORKDIR /code
RUN python3 setup.py install
RUN python3 setup.py test
