site_name: Documentation
site_description: eduVPN for Linux
docs_dir: md
site_dir: site
theme:
    name: null
    custom_dir: 'eduvpn_theme/'
    navigation_depth: 3
nav:
    - 'About': index.md
    - 'Installation': installation.md
    - 'Usage': usage.md
    - 'Support': support.md
use_directory_urls: False
markdown_extensions:
    - smarty
    - sane_lists
    - toc:
       permalink: "#"
       baselevel: 1
       toc_depth: 2-3