# python-eduvpn-client - The GNU/Linux eduVPN client and Python API
#
# Copyright: 2017, The Commons Conservancy eduVPN Programme
# SPDX-License-Identifier: GPL-3.0+

from typing import Any, Iterable

builder_files = ...  # type: Iterable[str]

class EduVpnApp:
    selected_meta = ...  # type: Any
    prefix = ...  # type: Any
    builder = ...  # type: Any
    window = ...  # type: Any
    verifier = ...  # type: Any
    def __init__(self) -> None: ...
    def run(self): ...
    def add(self, _): ...
    def delete(self, _): ...
    def select(self, _): ...
    def vpn_change(self, *args, **kwargs): ...
    def switched(self, selection, _): ...
